version: '3.8'

name: training-portal

services:
    backend:
        build:
            context: ..
            dockerfile: deploy/Dockerfile
        container_name: training-portal-backend
        ports:
            - '3000:3000'
        depends_on:
            - mongo
        environment:
            - PORT=3000
            - MONGO_URI=mongodb://mongo:27017/training-portal
            - JWT_SECRET=${JWT_SECRET:-default_secret}

    mongo:
        image: mongo
        container_name: mongo
        ports:
            - '27017:27017'
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data: